Feature/soundboard
tue-robotics/text_to_speech pull request #4
Opened 2017-05-08 19:05 UTC by MatthijsBurgh

@timple, ready for pull request?

2017-05-08 19:49 UTC, Timple commented
Yup

2017-05-08 19:54 UTC, reinzor commented
No clear pr imo, what is the refactor and what is the feature?

2017-05-09 06:45 UTC, Timple commented
True, pep8ify should have been seperate pull request

2017-05-10 09:02 UTC, Rayman requested changes
Looks good. After the small fix: :shipit:

2017-05-10 09:02 UTC, Rayman commented on scripts/text_to_speech_node.py
> +        self.samples_path = rospy.get_param("~samples_path", os.path.expanduser("~/MEGA/media/audio/soundboard"))
You should do the `os.path.expanduser` call later so people are able to use `~` in their parameters.

2017-05-10 13:21 UTC, Timple commented on scripts/text_to_speech_node.py
> +        self.samples_path = rospy.get_param("~samples_path", os.path.expanduser("~/MEGA/media/audio/soundboard"))
That does make sense!

2017-05-10 14:37 UTC, Rayman approved these changes

2017-05-10 14:57 UTC, merged